### ISSUE TITLE
error in picoquicdemo client: Assertion `server_name != NULL && "ptls_set_server_name MUST be called"' failed.

### ISSUE THREAD

**Issue by futile** [private-octopus/picoquic#260] opened 2018-07-27 14:21 UTC
I get the following logs (including a crash on the client) when running two `picoquicdemo`s (one server one client):

server:
```
/tmp/foo/picoquic]$ ./picoquicdemo
Starting PicoQUIC server on port 4443, server name = ::, just_once = 0, hrr= 0
e6ab19794170159d: Receiving 1252 bytes from 127.0.0.1:42169 at T=0.000000 (571fbc332ece7)
e6ab19794170159d:     Type: 2 (initial), S0, Version ff00000d, <e6ab19794170159d>, <0f4ae98dee5a33a6>, Seq: 0, pl: 1207
e6ab19794170159d:     Decrypted 1207 bytes
e6ab19794170159d:     Crypto HS frame, offset 0, length 226: 010000de0303527f...
e6ab19794170159d:     padding, 977 bytes

e6ab19794170159d: 0.004209 : Connection established, state = 11, from length: 16
e6ab19794170159d: Client address: 127.0.0.1, port 47524
e6ab19794170159d: SNI not received.
e6ab19794170159d: Received ALPN: hq-11
e6ab19794170159d: Received transport parameter TLS extension (46 bytes):
e6ab19794170159d: Proposed version: ff00000d
e6ab19794170159d:     Extension list (40 bytes):
e6ab19794170159d:         Extension type: 0, length 4 (0x0000 / 0x0004), 0000ffff
e6ab19794170159d:         Extension type: 1, length 4 (0x0001 / 0x0004), 00100000
e6ab19794170159d:         Extension type: 2, length 2 (0x0002 / 0x0002), 4000
e6ab19794170159d:         Extension type: 3, length 2 (0x0003 / 0x0002), 000f
e6ab19794170159d:         Extension type: 5, length 2 (0x0005 / 0x0002), 05a0
e6ab19794170159d:         Extension type: 8, length 2 (0x0008 / 0x0002), 4000
e6ab19794170159d: Connection state = 6
e6ab19794170159d: Sending 1252 bytes to 127.0.0.1:42169 at T=0.000000 (571fbc332ece7)
e6ab19794170159d:     Type: 2 (initial), S0, Version ff00000d, <0f4ae98dee5a33a6>, <94c205cb9ec6add8>, Seq: 0, pl: 131
e6ab19794170159d:     Decrypted 131 bytes
e6ab19794170159d:     ACK (nb=0), 0
e6ab19794170159d:     Crypto HS frame, offset 0, length 122: 0200007603036722...

e6ab19794170159d: Sending 1076 bytes to 127.0.0.1:42169 at T=0.000000 (571fbc332ece7)
e6ab19794170159d:     Type: 4 (handshake), S0, Version ff00000d, <0f4ae98dee5a33a6>, <94c205cb9ec6add8>, Seq: 0, pl: 1032
e6ab19794170159d:     Decrypted 1032 bytes
e6ab19794170159d:     Crypto HS frame, offset 122, length 1027: 0800005d005b0010...

oquic/picoquic/sender.c:779 [picoquic_retransmit_needed]: Retransmit packet type 2, pc=2, seq = 0, is_client = 0

oquic/picoquic/sender.c:779 [picoquic_retransmit_needed]: Retransmit packet type 4, pc=1, seq = 0, is_client = 0

oquic/picoquic/sender.c:779 [picoquic_retransmit_needed]: Retransmit packet type 4, pc=1, seq = 1, is_client = 0

oquic/picoquic/sender.c:779 [picoquic_retransmit_needed]: Retransmit packet type 2, pc=2, seq = 1, is_client = 0

^C
```

client:
```
[/tmp/foo/picoquic]$ ./picoquicdemo 127.0.0.1 4443
Starting PicoQUIC connection to server IP = 127.0.0.1, port = 4443
quic/picoquic/quicctx.c:202 [picoquic_create]: Ticket file <demo_ticket_store.bin> not created yet.

Sending 1252 bytes to 127.0.0.1:4443 at T=0.000000 (571fbc332e222)
    Type: 2 (initial), S0, Version ff00000d, <e6ab19794170159d>, <0f4ae98dee5a33a6>, Seq: 0, pl: 1207
    Decrypted 1207 bytes
    Crypto HS frame, offset 0, length 226: 010000de0303527f...
    padding, 977 bytes

Select returns 1252, from length 16
Receiving 1252 bytes from 127.0.0.1:4443 at T=0.007075 (571fbc332fdc5)
    Type: 2 (initial), S0, Version ff00000d, <0f4ae98dee5a33a6>, <94c205cb9ec6add8>, Seq: 0, pl: 131
    Decrypted 131 bytes
    ACK (nb=0), 0
    Crypto HS frame, offset 0, length 122: 0200007603036722...

oquic/picoquic/packet.c:475 [picoquic_decrypt_packet]: PN dec not ready, type: 4, epoch: 2, pc: 1, pn: -1

Receiving 1076 bytes from 127.0.0.1:4443 at T=0.007075 (571fbc332fdc5)
    Type: 4 (handshake), S0, Version ff00000d, <0f4ae98dee5a33a6>, <94c205cb9ec6add8>, Seq: ffffffff, pl: 1052
   Header or encryption error: 403.

picoquicdemo: /tmp/foo/picotls/lib/openssl.c:1008: verify_cert_chain: Assertion `server_name != NULL && "ptls_set_server_name MUST be called"' failed.
[1]    28849 abort (core dumped)  ./picoquicdemo 127.0.0.1 4443
```

As can be seen the client crashes with a failed assertion, and the server starts retransmitting because it gets no replies anymore (after some seconds I Ctrl-C'd the server because the client was already gone).

I used two unmodified, fresh versions of `picotls` and `picoquic` and built them as documented (`cmake . && make` for both). The commit I used was ef5a2520bc6be66d271afce0d2ceb92036f11d74

Am I doing something wrong?

Edit:
My System: Arch Linux x86_64, kernel 4.14.56-1-lts

**Comment by huitema** [comment] 2018-07-27 16:11
I think that you are hitting bug #210.

By default, the TLS stack on the client verifies the TLS certificate of the server using code from OpenSSL. That code will compare the server name in the TLS certificate to the "server name" parameter set on the client, and will assert or crash if there is no server name specified.

In the short term, you can work around the issue by specifying a server name and a certificate authority as command line parameters for the client. I assume that the server is using the default test certificate that comes with the code. This certificate is for "test.example.com", and it is signed by a "test" Certificate Authority. The work around would be to call the client as:
```
picoquicdemo -n test.example.com -t ./certs/test-ca.crt 127.0.0.1 4433
```
We need to fix this issue in the long term. The simplest solution would be to not attempt certificate verification at all if the client does not specify a server name. Did not do that yet because it is very insecure, but maybe we should just do that patch.

**Comment by futile** [comment] 2018-07-28 14:15
Thanks for the quick reply!

The work around makes it work for me. Maybe it's enough if this is just mentioned somewhere (e.g., in the README?)

**Comment by huitema** [comment] 2018-07-28 15:55
I intend to actually fix the issue. Lots of potential users are interested in simple tests and don't care all that much for X509/PKI purity, so the checks are just annoying. But of course you do want the checks in production. I need to find the right signal for the application to state "don't check".

**Comment by huitema** [comment] 2018-08-03 20:42
Fixed with PR #263.

**Comment by hoang-tranviet** [comment] 2019-02-07 15:07
I got a similar error on client( with segfault):
This is on current master branch.
```
./picoquicdemo 42.0.1.1  4443                               
Starting PicoQUIC connection to server IP = 42.0.1.1, port = 4443
No server name specified, certificate will not be verified.
Segmentation fault
```
A workaround on Linux is to put server name + IP in /etc/hosts and specify server via this name.

**Comment by huitema** [comment] 2019-02-07 17:24
You can use the '-n' command line parameter to specify a name, without relying on /etc/hosts

**Comment by huitema** [comment] 2019-02-07 19:24
Reopening. There is a regression, due to code added for support of the "NEW TOKEN" function.

**Closed** 2019-02-07 20:57 UTC
