### ISSUE TITLE
Why protocol error 0x4 triggered?

### ISSUE THREAD

**Issue by dongsf** [private-octopus/picoquic#1415] opened 2022-12-02 06:08 UTC
The server side of picoquic did't send max_streams frame prospectively, and fall into protocol error 0x4.
How to avoid this situation?

**Comment by dongsf** [comment] 2022-12-02 06:10
[6c2d4d4fb759c2c8.server.qlog.zip](https://github.com/private-octopus/picoquic/files/10138521/6c2d4d4fb759c2c8.server.qlog.zip)
[6c2d4d4fb759c2c8.zip](https://github.com/private-octopus/picoquic/files/10138525/6c2d4d4fb759c2c8.zip)

**Comment by huitema** [comment] 2022-12-02 07:52
I think that the main issue is that streams are not getting closed quickly enough, or alternately that new "max_streams" frame are not been sent fast enough. That's a tuning issue. The max streams value is updated when half the stream budget has been consumed. If too many streams are left open, that will happen rarely.

But for me the critical part of the log is:
```
[692554648, 0, "transport", "datagram_received", { "byte_length": 317}],
[692554648, 0, "transport", "packet_received", { "packet_type": "1RTT", "header": { "packet_size": 317, "packet_number": 269791, "dcid": "9e4b0e2aac4c89aa" }, "frames": [{ 
    "frame_type": "time_stamp", "time_stamp": 86590711}, { 
    "frame_type": "ack", "ack_delay": 1414, "acked_ranges": [[35219, 35221]]}, { 
    "frame_type": "stream", "id": 0, "offset": 174517, "length": 41, "fin": false , "begins_with": "0000260000c0a801"}, { 
    "frame_type": "stream", "id": 0, "offset": 174558, "length": 41, "fin": false , "begins_with": "0000260000c0a801"}, { 
    "frame_type": "stream", "id": 0, "offset": 174599, "length": 41, "fin": false , "begins_with": "0000260000c0a801"}, { 
    "frame_type": "stream", "id": 16422, "offset": 0, "length": 37, "fin": false , "begins_with": "7762722e31363639"}, { 
    "frame_type": "stream", "id": 16426, "offset": 0, "length": 37, "fin": false , "begins_with": "7762722e31363639"}, { 
    "frame_type": "stream", "id": 16430, "offset": 0, "length": 37, "fin": false , "begins_with": "7762722e31363639"}]}],
[692554768, 0, "info", "message", { "message": "Protocol error (4), stream_id 16430 < max_stream_id 16428 !"}],
[692554771, 0, "info", "message", { "message": "Protocol error 0x4"}],
```
The server receives a frame that opens stream 16430, but max_stream_id is set to 16428. The client and the server do not appear to agree on what the stream limit should be. Stream 16430 is a client initiated unidirectional stream. The limit was previously updated by:
```
[575660619, 1, "transport", "packet_sent", { "packet_type": "1RTT", "header": { "packet_size": 1424, "packet_number": 32312, "dcid": "e9321a235b242db8" }, "frames": [{ 
    "frame_type": "time_stamp", "time_stamp": 71957577}, { 
    "frame_type": "ack", "ack_delay": 1301, "acked_ranges": [[222749, 227352]]}, { 
    "frame_type": "max_streams", "stream_type": "unidirectional", "maximum": 4108}, { 
    "frame_type": "stream", "id": 13259, "offset": 5, "length": 1389, "fin": false , "has_length": false, "begins_with": "00001e137b226370"}]}],
```
The maximum stream value should be: 2 (first unidir styream from client) + 4*(4108-1) = 16,430. The client is correct, the server is wrong. The server value is erroneous, and also suspicious. Looks like "4*(4108-1)", which is the formula for bidir streams.

**Comment by huitema** [comment] 2022-12-02 19:57
To be sure, I need to add a test case that reproduces you issue. I think that means:

1- Connection from server to client
2- Start bidir stream 0, which will be kept open and send data the whole time
3- Send series of "small" messages as short unidirectional streams in both directions, with the number of messages larger than the number of streams

Is there something else? Maybe cause stress conditions somehow, e.g., by delaying the closure of streams?

I want to fix the code -- that scenario is also required for Media over QUIC. But I am traveling, and cannot promise to do that quickly. As a workaround, you may try to increase the value of "max number of unidirectional streams" in the initial transport parameters on both client and servers.

**Comment by huitema** [comment] 2022-12-02 20:31
@dongsf I think that you can fix the error by verifying that the initial value of the "max number of unidirectional streams" is a valid number. That's a quirk in the code, which I think I will have to fix. The rules are:

* Client side: max unidirectional stream ID is for streams sent by server, should be set `4*N + 3` where N is the number of streams opened at the same time
* Server side: max unidirectional stream ID is for streams sent by client, should be set `4*N + 2` where N is the number of streams opened at the same time

**Comment by huitema** [comment] 2022-12-03 21:28
Another observation: looking in the QLOG, I see lines like:
```
[119101225, 1, "transport", "packet_sent", { "packet_type": "1RTT", "header": { "packet_size": 39, "packet_number": 16278, "dcid": "e9321a235b242db8" }, "frames": [{ 
    "frame_type": "stream_data_blocked", "stream_id": 3011, "limit": 65535}, { 
    "frame_type": "padding"}]}],
```
That means the server opened a unidirectional stream, sent 64KB, and then was blocked by the "max data per stream" limit. It is unblocked 75ms later:
```
[119173480, 1, "transport", "packet_received", { "packet_type": "1RTT", "header": { "packet_size": 1440, "packet_number": 40898, "dcid": "51bfbc8a2c8c1f28" }, "frames": [{ 
    "frame_type": "time_stamp", "time_stamp": 14918424}, { 
    "frame_type": "ack", "ack_delay": 32, "acked_ranges": [[16270, 16270], [16222, 16264]]}, { 
    "frame_type": "max_stream_data", "stream_id": 3011, "maximum": 196605}, { 
    "frame_type": "stream", "id": 3014, "offset": 3751, "length": 1386, "fin": false , "has_length": false, "begins_with": "170303061e000000"}]}],
 ```
Still, that means that the data to be sent are delayed by 75ms (1RTT?) because of this flow control issue.

Potential solution: increase the value of the transport parameter:
```
    "initial_max_stream_data_uni" : 65535,
```
The picoquic code increases the size of the per stream max data once the allowed value is half consumed. This will cause delays if the window is less than twice the bandwidth delay product. Picking a very large per stream value is probably safe, because the receivers are protected by the global flow control limit and by the limit on the number of streams, and because well behaved senders are limited by congestion control.

**Comment by dongsf** [comment] 2022-12-05 03:39
I used stream 0 as long opened channel , and other streams carried burst data, The default initial configs is not suit my case.
Thank you for all your reply

**Comment by dongsf** [comment] 2022-12-05 03:57
It's kind of proxy over Quic. stream 0 carry control messages, and relay data be forward over amount of  streams that always increased, and data-relay streams are closed while the proxy be disconnected.

**Comment by huitema** [comment] 2022-12-05 05:21
In your scenarios, how to you manage flow control? If messages arrive faster than the connection can carry, what happens?

**Comment by dongsf** [comment] 2022-12-05 06:38
It depends. stream-like message (tcp) have their own flow control, so I suspend relay while overflowing. But datagrams are droped (datagrams are carried by quic's datagram ).

**Comment by huitema** [comment] 2022-12-05 07:32
Yes, "stream-like message (tcp) have their own flow control". But if you keep opening new streams at the API while the connection is slow, you can build a big queue. I suspect that's what happened. The error 04 is a bug, but it would not have been triggered if the total number of open flow had not grown.

Maybe I need to add an API so applications know when the stream creation limits are reached. And an event to tell the application when the creation is possible again. Any preference for how this should be exposed in the API?

**Comment by huitema** [comment] 2022-12-05 20:25
There are a couple of ways to do that. Yes, making limits visible is one way. Another way would be add an event for "stream finished", matching when picoquic deletes the context of the stream -- usually because it has been fully acknowledged by the peer, but could also be because of an error.

**Comment by huitema** [comment] 2022-12-12 06:31
@dongsf you may want to look at the PR #1420. It was specifically designed to test your scenario. The new tests surfaced a number of issues, including a repro of the "error 04". These issues are fixed. The internal changes are extensive, but the API did not change.

**Comment by huitema** [comment] 2023-02-03 03:18
Close the issue as it is fixed.

**Closed by huitema** 2023-02-03 03:18 UTC
