### ISSUE TITLE
picoquic's bandwidth is smaller than tcp in openwrt (mt7261)

### ISSUE THREAD

**Issue by dongsf** [private-octopus/picoquic#1400] opened 2022-08-29 06:53 UTC
I have tested picoquic in multi-platform, and find out that the bandwidth in openwrt (mt7261 soc) is too much smaller than tcp (tcp is 3.5-4.5MB/s, the picoquic is 2.0-2.5MB/s). but in other platforms, they are closely.
I tested it with picoquic_sample with perflog enabled. Is something wrong?
[picoquic_perf.csv](https://github.com/private-octopus/picoquic/files/9442192/picoquic_perf.csv)

**Comment by dongsf** [comment] 2022-08-29 07:33
[picoquic_perf.csv](https://github.com/private-octopus/picoquic/files/9442438/picoquic_perf.csv)
[d8a6192212aa3573.client.txt](https://github.com/private-octopus/picoquic/files/9442442/d8a6192212aa3573.client.txt)

**Comment by huitema** [comment] 2022-08-29 16:37
I see that you are using the "picoquic sample" code. This is a simple program, meant to demonstrate the picoquic APIs. The program "picoquic demo" has more configuration options -- for example, it will let you configure different congestion control algorithms, instead of always using BBR as in the sample.

**Comment by dongsf** [comment] 2022-08-31 09:26
I tested it with picoquic demo. the demo was running in the router, and compared with wget and iperf3（Server is the same one）. 
The server side:
./picoquicdemo -k server-key.pem -c ca-cert.pem -p 4433 -F server_log.csv -G reno -q ./

The client side :
root@4G_Wireless:/tmp/mp# ./picoquicdemo -q ./  -a perf 39.103.209.220 4433 "*1:0:-:397:50000000;"
Starting Picoquic (v1.02) connection to server = 39.103.209.220, port = 4433
Getting ready to run QUICPERF
Careful: NULL SNI is incompatible with HTTP 3. Expect errors!
Max stream id bidir remote before start = 0 (0)
Starting client connection. Version = 1, I-CID: c1c622f6c1ab2511
Max stream id bidir remote after start = 0 (0)
Waiting for packets.
Client port (AF=2): 48855.
Negotiated ALPN: perf
Almost ready!

Connection established. Version = 1, I-CID: c1c622f6c1ab2511, verified: 1
The connection is closed!
Quic Bit was NOT greased by the client.
Quic Bit was NOT greased by the server.
ECN was not received.
ECN was not acknowledged.
Connection_duration_sec: 25.082542
Nb_transactions: 1
Upload_bytes: 397
Download_bytes: 50000000
TPS: 0.039868
Upload_Mbps: 0.000127
Download_Mbps: 15.947347
max_data_local: 254803968
max_max_stream_data_local: 169869312
max_data_remote: 1048576
max_max_stream_data_remote: 2048
ack_delay_remote: 1000 ... 10000
max_ack_gap_remote: 32
ack_delay_local: 10000 ... 25000
max_ack_gap_local: 2
max_mtu_sent: 1440
max_mtu_received: 1440
Client exit with code = 0

wget in client: 
root@4G_Wireless:/tmp/mp# wget http://39.103.209.220:8080/tmp/tmpfile_50MB
--2022-08-31 08:01:54--  http://39.103.209.220:8080/tmp/tmpfile_50MB
Connecting to 39.103.209.220:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52428810 (50M)
Saving to: 'tmpfile_50MB'

tmpfile_50MB                                               100%[=======================================================================================================================================>]  50.00M  3.49MB/s    in 10s     

2022-08-31 08:02:04 (4.78 MB/s) - 'tmpfile_50MB' saved [52428810/52428810]

iperf test in client:

root@4G_Wireless:/tmp/mp# iperf3 -c 39.103.209.220 -R -u -b 40MB
Connecting to host 39.103.209.220, port 5201
Reverse mode, remote host 39.103.209.220 is sending
[  4] local 10.113.16.62 port 46316 connected to 39.103.209.220 port 5201
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-1.00   sec  4.49 MBytes  37.7 Mbits/sec  0.439 ms  0/3442 (0%)  
[  4]   1.00-2.00   sec  4.19 MBytes  35.1 Mbits/sec  0.343 ms  2/3217 (0.062%)  
[  4]   2.00-3.00   sec  5.40 MBytes  45.4 Mbits/sec  0.431 ms  1/4141 (0.024%)  
[  4]   3.00-4.00   sec  4.80 MBytes  40.2 Mbits/sec  0.538 ms  0/3680 (0%)  
[  4]   4.00-5.00   sec  4.81 MBytes  40.3 Mbits/sec  0.565 ms  0/3685 (0%)  
[  4]   5.00-6.00   sec  4.71 MBytes  39.6 Mbits/sec  0.253 ms  0/3614 (0%)  
[  4]   6.00-7.00   sec  4.73 MBytes  39.7 Mbits/sec  0.341 ms  0/3627 (0%)  
[  4]   7.00-8.00   sec  4.81 MBytes  40.2 Mbits/sec  0.430 ms  0/3686 (0%)  
[  4]   8.00-9.00   sec  4.59 MBytes  38.6 Mbits/sec  0.420 ms  0/3516 (0%)  
[  4]   9.00-10.00  sec  4.98 MBytes  41.6 Mbits/sec  0.264 ms  0/3816 (0%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Jitter    Lost/Total Datagrams
[  4]   0.00-10.00  sec  48.2 MBytes  40.4 Mbits/sec  0.106 ms  3/36921 (0.0081%)  
[  4] Sent 36921 datagrams

iperf Done.

qlogs:

[picoquicdemo.zip](https://github.com/private-octopus/picoquic/files/9460310/picoquicdemo.zip)

**Comment by huitema** [comment] 2022-08-31 19:38
It looks like an interaction between the openwrt router and the congestion control used in picoquic. In your example, you started the server with the "new reno" algorithm:
```
./picoquicdemo -k server-key.pem -c ca-cert.pem -p 4433 -F server_log.csv -G reno -q ./
```
We might get better performance by specifying "cubic" or "bbr" on the server instead of "reno", but even reno should get better performance than what we observe. When I look at the traces, I see the following broad pattern:

![image](https://user-images.githubusercontent.com/7464128/187755529-66c71893-78cf-49c8-a5b7-35532393e4da.png)

The startup phase concludes with an initial set of losses, the window is halved from 420KB to 210KB, but subsequent losses cause the window to be halved again, to 105KB. The congestion window will then grow very slowly, 1 packet per roundtrip using reno's congestion avoidance rule, until it reaches 309KB at time=22.7 seconds after start of connection. Then there are new series of losses, causing the window to shrink to 156KB and then 78KB.

The performance issues are mostly due to the start phase ending with a window almost twice or thrice too small, causing the beginning of the transmission to run much too slowly. It takes a long time for the congestion algorithm to catch something like that.

Looking at the log, I find two main issues:

1) An a couple of occasions, I see successive losses causing the CWIN to shrink twice. This is only supposed to happen if the lost packets were sent after the window shrank, but in at least one case this is not the case. That a bug, and should be fixed. However, that bug does not happen during startup. 

2) The client sends way too few ACKs. In the beginning of the traces, I see ACKs sent by the client after packets 225, 270, 545, 564 and then 764. This is not expected, and the intervals are much higher than specified in the ACK_FREQUENCY frames. This points to a scheduling problem on the client side, as if the client was busy receiving and never getting to sending.

I wonder what may be causing the scheduling issue on the client side. The sender sends up to a few hundred packets per second, but that should not be enough to saturate the client and cause delays. Are you running the client under some sort of debugger?

**Comment by huitema** [comment] 2022-08-31 20:29
@dongsf I quickly prepared PR #1401 that should mitigate the scheduling issue at the receiver. Can you test whether that gets better performance in your test configuration?

**Comment by dongsf** [comment] 2022-09-01 08:57
Here is the new test.

iperf3 :
root@4G_Wireless:/tmp/mp# iperf3 -c 39.103.209.220 -R 
Connecting to host 39.103.209.220, port 5201
Reverse mode, remote host 39.103.209.220 is sending
[  4] local 10.113.16.62 port 41048 connected to 39.103.209.220 port 5201
[ ID] Interval           Transfer     Bandwidth
[  4]   0.00-1.00   sec  2.81 MBytes  23.5 Mbits/sec                  
[  4]   1.00-2.00   sec  4.79 MBytes  40.1 Mbits/sec                  
[  4]   2.00-3.00   sec  5.13 MBytes  43.0 Mbits/sec                  
[  4]   3.00-4.00   sec  5.19 MBytes  43.6 Mbits/sec                  
[  4]   4.00-5.00   sec  5.38 MBytes  45.1 Mbits/sec                  
[  4]   5.00-6.00   sec  5.52 MBytes  46.3 Mbits/sec                  
[  4]   6.00-7.00   sec  4.30 MBytes  36.0 Mbits/sec                  
[  4]   7.00-8.00   sec  5.91 MBytes  49.7 Mbits/sec                  
[  4]   8.00-9.01   sec  6.75 MBytes  56.4 Mbits/sec                  
[  4]   9.01-10.00  sec  6.25 MBytes  52.5 Mbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  54.8 MBytes  46.0 Mbits/sec    1             sender
[  4]   0.00-10.00  sec  52.9 MBytes  44.4 Mbits/sec                  receiver

iperf Done.

bbr & cubic & reno & fast :
[picoquic_perf_test.zip](https://github.com/private-octopus/picoquic/files/9468358/picoquic_perf_test.zip)

picoquic demo was running in the router directly.

**Comment by huitema** [comment] 2022-09-01 15:25
I am looking at the new traces. The protocol implementation issues are fixed, and the reno download speed went from 15-16 Mbps to 19-20 Mbps. But the scheduling issues are only partially fixed.

The client -- not the server -- is starving for CPU. It is forever busy receiving data on the socket, and only sends acknowledgements rarely. The initial fix forced trying to send an ack every 5 milliseconds, but that is not sufficient, I need something more forceful.

**Comment by huitema** [comment] 2022-09-03 01:12
@dongsf I would like to know whether the new version of PR #1401 improves the performance with openwrt.

The PR addresses two issues:

* Picoquic was in some case allowing loss of packets sent before entering recovery to force a new recovery. The recent traces show that this issue is fixed.
* The default socket loop of Picoquic was behaving badly when the client was CPU-bound, causing acknowledgements to arrive too late, and slowing down the sender. This was partially fixed in the first version of the PR, should be better fixed now.

Once the issues are addressed, I suspect that the performance will still be lower than TCP. QUIC requires encryption, TCP does not. If the client or server platform does not have enough computing capacity for handling both transmission and encryption, the data rate will be lower. You could test that by comparing QUIC to HTTPS instead of HTTP.

**Comment by dongsf** [comment] 2022-09-05 07:05
Sorry for the late reply. I think the two issues are fixed. here is the qlog.
[fixed_ack_bbr.zip](https://github.com/private-octopus/picoquic/files/9487442/fixed_ack_bbr.zip)

As you said, the performance is still be lower than TCP. How to remove encryption to get higher performance?

**Comment by huitema** [comment] 2022-09-05 07:23
You cannot remove encryption. But you can try using a different algorithm. The platform that you are using apparently does not have AES encryption acceleration, so you might be able to get better performance by using the ChaCha/Poly algorithm -- in the picoquicdemo client, set the option '-C 20'.

**Comment by davidfdzp** [comment] 2022-09-05 08:13
There was this proposed: https://datatracker.ietf.org/doc/draft-banks-quic-disable-encryption

**Comment by dongsf** [comment] 2022-09-05 08:38
> performance



> You cannot remove encryption. But you can try using a different algorithm. The platform that you are using apparently does not have AES encryption acceleration, so you might be able to get better performance by using the ChaCha/Poly algorithm -- in the picoquicdemo client, set the option '-C 20'.



> You cannot remove encryption. But you can try using a different algorithm. The platform that you are using apparently does not have AES encryption acceleration, so you might be able to get better performance by using the ChaCha/Poly algorithm -- in the picoquicdemo client, set the option '-C 20'.

Using  ChaCha20 get better performance in this platform.
Shoud I refer to https://github.com/private-octopus/picoquic/issues/1120 if I want to disable the encryption?

**Comment by huitema** [comment] 2022-09-05 15:13
Yes, use #1120,  let's keep that discussion in one place.

**Comment by huitema** [comment] 2022-09-05 15:25
There is strong opposition in the WG to publishing any standard way to disable the encryption -- that's why Nick Bank's draft was not adopted and expired. If there was a standard way to disable encryption, some deployment might be compelled to use it, and the security of the Internet will be affected.

What kind of hardware platform are you using in the openwrt tests? If you want high performance there, you could you test with a router that uses a modern version of the ARM processor. Modern ARM supports AES acceleration. Or, if you want to test whether the openwrt router supports QUIC well, you could use a PC as a server, and do the tests with a client on the other side of the router.

**Comment by dongsf** [comment] 2022-09-06 13:32
> There is strong opposition in the WG to publishing any standard way to disable the encryption -- that's why Nick Bank's draft was not adopted and expired. If there was a standard way to disable encryption, some deployment might be compelled to use it, and the security of the Internet will be affected.
> 
> What kind of hardware platform are you using in the openwrt tests? If you want high performance there, you could you test with a router that uses a modern version of the ARM processor. Modern ARM supports AES acceleration. Or, if you want to test whether the openwrt router supports QUIC well, you could use a PC as a server, and do the tests with a client on the other side of the router.

The router in my case is a proxy , and I want to redirect data to a proxy-server by picoquic. So I have to run picoquic in the router.
The hardware platform is MT7621 (MIPS32 880Mhz)，I tested with the  last PR https://github.com/private-octopus/picoquic/pull/1401 . The maximum performance is around 35Mbps consumed 23% cpu . The single-path and multi-path have the same result .
I will try https://github.com/private-octopus/picoquic/issues/1120 to get better performance.

**Comment by huitema** [comment] 2022-09-06 14:17
If you are building a proxy, disabling the encryption will not solve your problem because you cannot disable it on the clients using the proxy, or on the servers that the proxy connects to. But there may be a solution.

The specifications of the MT7621 mention "VPN Support" and "200 Mbps Crypto Suite". That crypto suite most probably has an implementation of AES, optimized for the platform. If you could use that implementation under the Picotls API and then call this API from Picoquic, you would most probably improve performance.

**Comment by huitema** [comment] 2022-09-06 15:06
There is something else. You say that "The maximum performance is around 35Mbps consumed 23% cpu." That means the server is not CPU limited. If I look at the [openwrt benchmarks for OpenSSL](https://openwrt.org/docs/guide-user/perf_and_log/benchmark.openssl), I see that most routers based on MT7621 process AES128 at 11 to 12 Megabytes per second (100 Mbps), with the Netgear R6260 achieving twice that -- 24 MBps, nearly 200 Mbps.

There is something else happening. Maybe the limitation comes from the client. Or maybe there is a UDP scheduling issue. If you want to dig further, you need to collect data showing details of execution time by function on the server and client. Also, are you using the two processor cores or just one?

**Comment by dongsf** [comment] 2022-09-07 02:50
> 

The server is a VPS with very high computing power.  "The maximum performance is around 35Mbps consumed 23% cpu." is in side MT7621, so the cpu is not limited in the client. I tested it with picoquicdemo and my test-app (with libevent) , those two are single-core driving

**Comment by dongsf** [comment] 2022-09-07 02:51
> 

The server is a VPS with very high computing power.  "The maximum performance is around 35Mbps consumed 23% cpu." is in side MT7621, so the cpu is not limited in the client. I tested it with picoquicdemo and my test-app (with libevent) , those two are single-core driving

**Comment by huitema** [comment] 2022-09-07 04:37
If it was my product, I would try to do a performance analysis, see where the time is spent inside the code. The process appears CPU limited, but you indicate only 23% CPU usage -- or maybe 46% of a single core. Where are the other 54%? It is tempting to say "encryption", but encryption and decryption would normally be counted in the 23 or 46%. There is something else happening as well. I suspect this is related to UDP. The cost of handling UDP would appear as "system", because it happens inside system calls.

In theory, Picoquic addresses the cost of the UDP API by using UDP GSO. But there are cases in which UDP GSO is not available, either because the Linux kernel is too old, or because the network driver does not support GSO. You may want to check that.

**Comment by dongsf** [comment] 2022-09-09 10:34
The performance is blocked by saving qlog to filesystem . The performance is close to TCP when qlog be disabled.
But , the performance in two real lte channel (multipath enabled ) didn't get better performance .  is #1400 have an effect on that?

**Comment by huitema** [comment] 2022-09-12 17:39
Yes, managing qlog and other logs can be very costly, involves parsing messages and writing on disk. It is indeed best to not enable it if you are concerned about performance.

In theory, multipath support allows for load balancing with several LTE connections. tests demonstrate that. But if you are limited by CPU, then using several connections will not improve performance.

**Comment by huitema** [comment] 2023-02-04 04:46
@dongsf Do you still consider this issue opened?

**Comment by huitema** [comment] 2023-04-27 00:59
Closing for now, as the issues appear fixed. Will revisit if this reproduces.

**Closed** 2023-06-19 00:05 UTC
